### PR TITLE
Add simple blkio read/write/total stats

### LINKED ISSUE #19: Add blkio stats
Dockerbeat should collect blkio statistics. Stats should be human-readable i.e should be read/write Bytes per second.

### PR DESCRIPTION
**Pull request by erwanncloarec**
Closes #19 
I have to do the same as network stats to store the latest data and send the diff, not the raw value.

### CODE REVIEW

**Comment by marminthibaut** [comment]
Good work :)

But is it possible to limit dependencies from calculator to external libraries? Your blkiocalculator depends on dockerclient stats type... I suggest to create a custom type BlkioData as you can see in networkcalculator.

What do you think about that?

**Comment by erwanncloarec** [comment]
I updated that, take a look.
Now we have the diff between last & current stats

**Comment by marminthibaut** [comment]
Perfect!

@erwanncloarec : Can you merge `develop` into your branch and add fields into `etc/fields`?

Thx

**Comment by erwanncloarec** [comment]
Done, OK to merge?

**Comment by marminthibaut** [comment]
Generate the new template and the new fields doc and merge is ok :)

**Pull request merged**
